#include <stdio.h>

// Main modules
#include "modules/dish.h"
#include "modules/customers.h"

// Extra modules
#include "modules/timecov.h"

void mainMenu() {
#ifdef _WIN32
    puts("Windows");
#elif __APPLE__
    puts("Mac OS X");
#elif __MACH__
    puts("Mac OS X");
#else
    puts("Linux-based System");
#endif
    TimeData *c_time = convertToTimeData(currentTime());
    printf("%s %s %s %s:%s:%s %d\n", c_time->s3wdays, c_time->s3months, c_time->pmdays,
            c_time->phours, c_time->pmins, c_time->psecs, c_time->years);
    puts("1. Add Dish");
    puts("2. Remove Dish");
    puts("3. Add Customer");
    puts("4. Search Customer");
    puts("5. View Warteg");
    puts("6. Order");
    puts("7. Payment");
    puts("8. Exit Warteg");
}

void splashScreen() {
    // generated by python code because I'm lazy to split it manually by lines.
    puts("                                                                                            ");
    puts("                                                                                            ");
    puts("                                                      ..`                                   ");
    puts("                  .//.                               /+++-   `    :/:                       ");
    puts("                  /MM:                               -/+/` .hm/   dMd                       ");
    puts("         :osso/`  /MM:   `+ss+:ss-  `/osso:   /so:sy: ss/ +yMMhs: dMd/sso:   +s+/sso-.+sso: ");
    puts("        hMdo+dMm. /MM:  .NMNyyNMM/ .NMmsyNMh  yMMmss- MMy :oMMy/- dMMdshMMo  mMMdsdMMMdshMMs");
    puts("        .-:--+MM/ /MM:  +MM-  /MM/ sMM`  +MM- yMM`    MMy  -MM+   dMm   dMm  mMm   mMm   hMN");
    puts("       `hMmhyhMM/ /MM:  +MM-  /MM/ sMM   /MM: yMM     MMy  -MM+   dMd   dMm  mMd   dMm   yMM");
    puts("       :MM+  +MM/ :MMo. .NMmsyNMM/ +MM+..yMM. yMM     MMy  -MMs`  dMd   dMm  mMd   dMm   yMM");
    puts("        sNMMNdMM/  smMM- `+syo+MM/  omMMMNh:  yMM     MMs   omMM: dMd   hMm  dMd   dMm   yMN");
    puts("         ``.` ``     `` .dds::hMm`  `..-..`````..`````...````....`...```...``...............");
    puts("                         -shhhyo`  `..............------------------------------------------");
    puts("                                   .+-/`   /::/    :::/`  .-o-`  `/::    -/    -o  :+   -/::");
    puts("                                   .s:s`  -+  /:  .o  :/    s    s`     `y+/   :++./s   //-+");
    puts("                                   .o-+.  `+--+`   +--/.    o    -/--   +.`+`  :-/+ o   :-` ");
    puts("                                    ```     ``      ``      `     ```   `         ` `       ");
    puts("                                                                                            ");
    puts("                                                                                            ");
}

int main() {
    int exit_flag = 1, option = 0;
    while (exit_flag) {
        // put menu
        mainMenu();
        while (option < 1 || option > 9) {
            printf(">> ");
            scanf("%d", &option);
            getchar();
        }

        switch (option) {
        case 1:
            puts("");
            tambahMenuBaru();
            break;
        case 2:
            puts("");
            hapusMenu();
            break;
        case 3:
            puts("");
            buatPelangganBaru();
            break;
        case 4:
            puts("");
            cariDataPelanggan();
            break;
        case 5:
            puts("");
            lihatSeluruhDataPelanggan();
            break;
        case 6:
            // order
            break;
        case 7:
            // payment
            break;
        case 8:
            // exit, don't forget to free the data :)
            freeDishesNode();
            freeCustomerNode();
            exit_flag = 0;
            break;
        }

        option = 0;
    }
    puts("");
    puts("Please expand your terminal to full screen!");
    puts("Press enter to continue...");
    getchar();
    // print splash-screen
    splashScreen();

    return 0;
}